### ISSUE TITLE
Running the install a second time in the same env results in a seg fault

### ISSUE THREAD

**Issue by sroet** [SBC-Utrecht/PyTomPrivate#105]
I am trying to improve the the install, but just for documentation: Currently, if you run the `pip setup.py install` a second time in the same env you end with a Segmentation fault. It does seem to correctly install, so it is just curious.

**Comment by McHaillet** [comment]
I dont have this issue anymore. Can we close the issue?

**Comment by sroet** [comment]
seems to be fixed on master, closing
