### ISSUE TITLE
suggested improvement for fullpipeline test

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/PyTomPrivate#139]
Suggestions to improve speed:
- boxsize should be set tp 160^3 pixels, this can still easily encompass ribosomes with overhang. I would suggest an attribute to the test class called `self.subtomo_boxsize_unbinned`. Steps that reconstruct binnen subtomograms can then set boxsize to `self.subtomo_boxsize_unbinned // binning`.
- The maximal resolution now is 10.5, even with a 2x subtomogram binning this is roughly still achievable because then nyquist would be `2 * 2.62 * binning = 10.48A`. Not doing the final unbinned step would greatly improve the speed of the test while it should still be able to almost reach the final resolution!
- the template box size is now 32^3, we could reduce this size to somewhere between 20-24 because the mask still fully fits within this (I believe). This saves some time in the rotation of the template.

Other suggestion:
- the template matching results are quite poor. On the same dataset in the tutuorial I was able to reach much better sensitivity (gold marker only detected after ribosomes) with a better optimized template. I think we could just switch to that one as it's already included in the repository data (tutorials folder). Now that I think of it, this one also has smaller size (see above)!

**Comment by sroet** [comment]
#145 solved this issue
