### ISSUE TITLE
Subtomogram averaging from patches

### ISSUE THREAD

**Issue by FridoF** [SBC-Utrecht/PyTomPrivate#16]
o  Reconstruct from (globally) aligned tiltseries (similar to provided python script reconstruction/reconstruct_subvolumes_INFR.py):
    - Box out patches (pick positions, also shifts (and their orientations) from particle list
    - Reconstruct using weighted ba-proj
    - Average
    - Compare average and resolution to that of original particles and particleList
    - Define proper format of ‘patch tilt series’ (e.g. dimx x dimy x Ntilt MRC file)
 o  Correlate patches with reference
    - Write down math ( = transformation of reference)
    - Implement different scoring functions (normalized CC, locally normalized CC, different apodizing/filtering)
    - Alternative scoring function from Mihajlo
    - Analyze shifts (how do they develop over time?, outlier problem, etc)
    - Reconstruct ‘polished ’volumes and average – assess change in resolution
 o  Refine particle alignment and polish again
    - Any significant improvements upon re-polishing?
 o  Compare to nearest-fiducial solutiono  Implement CTF correction on patches
    - Straightforward: simply take CTF model from existing CTF correction script and adjust defocus according to analytical model of sample (i.e., account for tilt and z-position of sample)
    - Phase-flipping
    - CTF multiplication (=Wiener Filter)
    - Evaluate improvement of resolution in averages
 o  Alternative reconstruction algorithms
    - Exact weighting bapro – dependence on specific filters
    - Gridding, iterative Fourier reconstruction
 o  Subtract background from surrounding in reconstruction
    - Reconstruct larger boxes – then subtract projection of larger box – with volume of interest zero-padded – from patch. To good approximation only particle projection should remain – if the reconstruction weighting did a good job.
    - Compare particle polishing for environment-cleaned particle projections
 o  Restrain motions of particles (similar to motionCorr)

**Comment by McHaillet** [comment]
I am closing this issue as it does not align with the current goals for pytom
