### ISSUE TITLE
Qt5Agg matplotlib backend shouldn't be forced outside of GUI code

### ISSUE THREAD

**Issue by the-lay** [SBC-Utrecht/PyTomPrivate#57]
Specifically this line, `matplotlib.use('Qt5Agg')` is all over the code, including some stuff that is not really GUI related.

Because of that, when you try running pytom on systems without X server (e.g., default Docker) some features may fail, including some test runs (see commit a4e385cb7e2a4b2385f5c94de5a3bc133d667d0c)

**Comment by McHaillet** [comment]
Most of this has been removed over time. I dont think its a big issue currently
